name: Build pgModeler

on:
  workflow_dispatch:

jobs:

  build:
  
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: pgmodeler/pgmodeler
          ref: main
          
      - name: Installing Qt framework
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.0
        
      - name: Running qmake
        run: cd $GITHUB_WORKSPACE; qmake pgmodeler.pro -r PREFIX=./build/pgModeler.app/Contents PGSQL_INC=`pg_config --includedir` PGSQL_LIB=`pg_config --libdir`/libpq.dylib
    
      - name: Building pgModeler
        run: make -j6
      
      - name: Deploying pgModeler
        run: make install
        
      - uses: actions/upload-artifact@v2
        with:
          name: pgModeler.app
          path: ./build
