# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: 'pgmodeler/pgmodeler'
          ref: 'main'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $HOMEBREW_PREFIX
        
      - name: Run a one-line script
        run: export HOMEBREW_PREFIX=$(brew --prefix)
        
      - name: Run a one-line script
        run: echo $HOMEBREW_PREFIX
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: brew install qt@5 libpq

      # Runs a set of commands using the runners shell
      - name: Build pgModeler
        run: |
          $HOMEBREW_PREFIX/opt/qt@5/bin/qmake PREFIX=./build/pgModeler.app/Contents PGSQL_LIB=$HOMEBREW_PREFIX/opt/libpq/lib/libpq.dylib PGSQL_INC=$HOMEBREW_PREFIX/opt/libpq/include -r pgmodeler.pro
          make && make install

      - uses: actions/upload-artifact@v2
        with:
          name: pgModeler.app
          path: ./build/pgModeler.app
